### ISSUE TITLE
Add alert: auspension+audit+online scores lower than a threshold

### ISSUE THREAD

**Issue by bjoerrrn** [bjoerrrn/storj-system-health.sh#5]

**Comment by dusselmann** [comment]
`for sat in `docker exec -i storagenode wget -qO - localhost:14002/api/sno | jq .satellites[].id -r`; do docker exec -i storagenode wget -qO - localhost:14002/api/sno/satellite/$sat | jq .id,.audits; done`

**Comment by bjoerrrn** [comment]
implemented with v1.5.2
